### ISSUE TITLE
Error when installing build-need package such as auto_gptq

### ISSUE THREAD

**Issue by jiwangyihao** [mmomtchev/pymport#174]
```
Collecting auto_gptq
  Using cached auto_gptq-0.7.1.tar.gz (126 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      Building cuda extension requires PyTorch (>=1.13.0) being installed, please install PyTorch first: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I have installed PyTorch before and it worked fine in my own project, I think maybe the environment using to build wheel is different from in-project.

**Comment by mmomtchev** [comment]
As you may have seen from my profile, I am currently living on social welfare because of an extortion involving the French police, judicial system and many open source projects. In order to intimidate me, people are posting simultaneously issues on my project. Currently, they have been trying to post with an ever increasing time difference between those issues so that I stop saying what I am saying at the moment, all while it remains obvious to everyone.
